name: Deploy Blazor WASM to GitHub Pages

on:
  push:
    branches:
      - main  # Triggers deployment on push to the main branch

jobs:
  build-wasm-demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'  # Specify the .NET version you're using

      - name: Restore dependencies
        run: dotnet restore src/BdziamUIExamples/BdziamUIExamples.csproj

      - name: Build the project
        run: dotnet build src/BdziamUIExamples/BdziamUIExamples.csproj --configuration Release --no-restore

      - name: Publish the project
        run: dotnet publish src/BdziamUIExamples/BdziamUIExamples.csproj --configuration Release --output ./output --no-build

      - name: copy index.html to 404.html
        run: cp release/wwwroot/index.html release/wwwroot/404.html

      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll

      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: ./output/wwwroot
